all: run

run:
	hpcli src.py
	hpcli src.py --num-layers 101
	hpcli src.py --num-layers 101 --hp-save config.yaml
	hpcli src.py --num-layers 101 --hp-save config.yaml --hp-list detail
	hpcli src.py -h
